# src/normalize/migrations/0001_initial.py
"""Hand-authored to match normalize/models.py (repo convention: no autogenerated migrations).

The build gate `makemigrations --check --dry-run` (Dockerfile) is the authoritative agreement
test between this file and the model -- it needs no DB. NormalizationRun has no FK, so this is a
single CreateModel; unique=True on run_ext_id renders as a field option, so no separate
AddConstraint op is required.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("run_ext_id", models.CharField(max_length=40, unique=True)),
                ("engine_version", models.CharField(max_length=64)),
                ("instance_id", models.CharField(max_length=64)),
                ("event_ext_id", models.CharField(max_length=64)),
                ("inputs_hash", models.CharField(max_length=64)),
                ("result_hash", models.CharField(max_length=64)),
                ("fingerprint", models.CharField(max_length=64)),
                ("signature", models.CharField(max_length=128)),
                ("lambda_value", models.FloatField()),
                ("n_boot", models.PositiveIntegerField()),
                ("seed", models.PositiveIntegerField()),
                ("audit_seq", models.PositiveIntegerField()),
                ("inputs", models.JSONField()),
                ("result", models.JSONField()),
                ("created_at", models.CharField(max_length=40)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "normalization_run",
                "ordering": ["id"],
            },
        ),
    ]
