# src/normalize/migrations/0002_resultpublication.py
"""Hand-authored to match normalize/models.ResultPublication (repo convention: no autogenerated
migrations). The build gate `makemigrations --check --dry-run` is the authoritative agreement test
between this file and the model -- it needs no DB.

ResultPublication has no FK (it names a run/event by ext_id string, like NormalizationRun), so this
is a single CreateModel plus one AddConstraint for the composite UNIQUE(event_ext_id, version) --
a multi-field UniqueConstraint in Meta.constraints renders as its own operation, exactly like the
events app's uniq_user_event_role.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normalize", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultPublication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name="ID")),
                ("event_ext_id", models.CharField(max_length=64)),
                ("run_ext_id", models.CharField(max_length=40)),
                ("version", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("provisional", "provisional"), ("final", "final")],
                                            default="final", max_length=16)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("published_by", models.CharField(blank=True, default="", max_length=64)),
                ("audit_seq", models.PositiveIntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "result_publication",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="resultpublication",
            constraint=models.UniqueConstraint(fields=("event_ext_id", "version"),
                                               name="uniq_event_result_version"),
        ),
    ]
